default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shotnr_development

test:
  <<: *default
  database: shotnr_test

production:
  <<: *default
  database: shotnr_production
  username: shotnr
  password: <%= ENV['SHOTNR_DATABASE_PASSWORD'] %>
